#!/usr/bin/env python3
"""
ANOMALY ENGINE — Phase VII
Persistent memory, anomaly detection, and narrative coherence validation

Core classes:
- AnomalyDetector: Identifies contradictions, outliers, state jumps, metaphysical mismatches
- MemoryGraph: Persistent graph of causally-linked events with query interface
- ContinuityEngine: Enforces narrative coherence and metaphysical law consistency
- PersistentNarrativeOrganism: Integration layer tying anomaly detection to fleet operations
"""

from .anomaly_detector import AnomalyDetector, AnomalyReport, AnomalyType
from .memory_graph import MemoryGraph, MemoryNode, MemoryEdge
from .continuity_engine import ContinuityEngine, ContinuityViolation
from .persistent_organism import PersistentNarrativeOrganism
from .cosmic_chaos import (
    UniverseMoodIndicator,
    DriftForecastEngine,
    ShipHoroscopeGenerator,
    UniversePatchNotesGenerator,
    CaptainForgotDinnerDetector,
    UniverseAchievementSystem,
    ShipMoodRing,
    WhatBrokeExplainer,
    MultiverseAlignmentScore,
    ShipDreamsGenerator,
    ShipToShipGossipEngine,
    MultiverseWeatherReport,
    MemoryGraphTimeLapseGenerator,
    WhatIfSimulator,
    ParadoxBuffer,
    UniverseLoreExpander,
    ChaosbringerPersonalityDriftTracker,
    UniverseMood,
    ShipMoodColor,
    DriftTrend,
    UniverseMoodReport,
    DriftForecast,
    ShipHoroscope,
    PatchNote,
    AchievementUnlocked,
    ShipDream,
    GossipEntry,
    MultiverseAlignmentReport,
)
from .micro_forking import (
    MicroForkingEngine,
    DashboardMockDataGenerator,
    PersonalitySeeds,
    CaptainsLogGenerator,
    CrossForkAnalytics,
    PersonalityDrivenAnomalyResponse,
    NarrativeContinuityAcrossForks,
    PersonalityType,
    PerturbationStrategy,
    PersonalityVector,
    ForkSnapshot,
    ForkResult,
    DivergenceAnalysis,
    CaptainLogEntry,
    IncidentReport,
    DashboardSnapshot,
)
from .cosmic_expansion import (
    TemporalWeatherService,
    AnomalyGenealogyEngine,
    DreamToRealityBleedoverDetector,
    MultiAgentGossipGraph,
    QuantumPatchNotesGenerator,
    WhatIfCaptainDidNothingSimulator,
    NarrativeGravityWell,
    EmergentCultureEngine,
    ContinuityParasiteScanner,
    CaptainMoodToUniverseFeedbackLoop,
    CausalityCreditScore,
    AnomalyCourtroom,
    ShipHobbiesModule,
    MultiverseWeatherRadar,
    ShipRumorMill,
    AnomalyZoo,
    NarrativeEconomy,
    ShipRelationshipMatrix,
    ContinuityBlackBox,
    WhyDidThisHappenEngine,
    TemporalWeather,
    AnomalyPedigree,
    BleedoverAlert,
    SocialNetwork,
    PatchNotes,
    SimulationResult,
    NarrativeMass,
    CultureUpdate,
    ParasiteScanResult,
    CourtVerdict,
    TemporalWeatherType,
    CultureTraitType,
    AnomalyCourtVerdict,
)
from .narrative_services import (
    ParadoxFireDepartment,
    TemporalArchaeologyDepartment,
    NarrativeTherapyCenter,
    TemporalGardeningService,
    NarrativeChemistryLab,
    ContinuityInsuranceCompany,
    TemporalPlumbingService,
    NarrativeRealEstateAgency,
    TemporalCateringService,
    NarrativeLandscapingCompany,
    TemporalCleaningService,
    NarrativePestControl,
    Paradox,
    FireSuppressionResult,
    ExcavatedEvent,
    ArchaeologicalReport,
    TherapySessionResult,
    TraumaDiagnosis,
    PruningResult,
    StoryElement,
    StoryCompound,
    CompoundAnalysis,
    InsurancePolicy,
    ContinuityBreach,
    ClaimResult,
    RepairResult,
    DrainResult,
    StoryLocation,
    Listing,
    TransactionResult,
    NarrativePest,
    ExterminationResult,
    SanitizationResult,
    StoryEnvironment,
    LandscapedEnvironment,
    ParadoxType,
    PestType,
    TraumaSeverity,
    InsuranceStatus,
)

# Phase X - Emergent Governance + Fleet Expansion
from governance import (
    GovernanceEngine,
    Constitution,
    FactionManager,
    DiplomacyEngine,
    LawRegistry,
    LawEngine,
)
from starship_archetypes import (
    MythosWeaver,
    AnomalyHunter,
    ContinuityGuardian,
)

__all__ = [
    # Phase VII - Anomaly Engine
    "AnomalyDetector",
    "AnomalyReport",
    "AnomalyType",
    "MemoryGraph",
    "MemoryNode",
    "MemoryEdge",
    "ContinuityEngine",
    "ContinuityViolation",
    "PersistentNarrativeOrganism",
    # Phase VII.5 - Cosmic Chaos Suite
    "UniverseMoodIndicator",
    "DriftForecastEngine",
    "ShipHoroscopeGenerator",
    "UniversePatchNotesGenerator",
    "CaptainForgotDinnerDetector",
    "UniverseAchievementSystem",
    "ShipMoodRing",
    "WhatBrokeExplainer",
    "MultiverseAlignmentScore",
    "ShipDreamsGenerator",
    "ShipToShipGossipEngine",
    "MultiverseWeatherReport",
    "MemoryGraphTimeLapseGenerator",
    "WhatIfSimulator",
    "ParadoxBuffer",
    "UniverseLoreExpander",
    "ChaosbringerPersonalityDriftTracker",
    # Phase VII.6 - Micro-Forking Evolution
    "MicroForkingEngine",
    "DashboardMockDataGenerator",
    "PersonalitySeeds",
    "CaptainsLogGenerator",
    "CrossForkAnalytics",
    "PersonalityDrivenAnomalyResponse",
    "NarrativeContinuityAcrossForks",
    # Data structures
    "UniverseMood",
    "ShipMoodColor",
    "DriftTrend",
    "UniverseMoodReport",
    "DriftForecast",
    "ShipHoroscope",
    "PatchNote",
    "AchievementUnlocked",
    "ShipDream",
    "GossipEntry",
    "MultiverseAlignmentReport",
    "PersonalityType",
    "PerturbationStrategy",
    "PersonalityVector",
    "ForkSnapshot",
    "ForkResult",
    "DivergenceAnalysis",
    "CaptainLogEntry",
    "IncidentReport",
    "DashboardSnapshot",
    # Phase VIII - Complete Cosmic Expansion Pack
    "TemporalWeatherService",
    "AnomalyGenealogyEngine",
    "DreamToRealityBleedoverDetector",
    "MultiAgentGossipGraph",
    "QuantumPatchNotesGenerator",
    "WhatIfCaptainDidNothingSimulator",
    "NarrativeGravityWell",
    "EmergentCultureEngine",
    "ContinuityParasiteScanner",
    "CaptainMoodToUniverseFeedbackLoop",
    "CausalityCreditScore",
    "AnomalyCourtroom",
    "ShipHobbiesModule",
    "MultiverseWeatherRadar",
    "ShipRumorMill",
    "AnomalyZoo",
    "NarrativeEconomy",
    "ShipRelationshipMatrix",
    "ContinuityBlackBox",
    "WhyDidThisHappenEngine",
    # Cosmic expansion data structures
    "TemporalWeather",
    "AnomalyPedigree",
    "BleedoverAlert",
    "SocialNetwork",
    "PatchNotes",
    "SimulationResult",
    "NarrativeMass",
    "CultureUpdate",
    "ParasiteScanResult",
    "CourtVerdict",
    "TemporalWeatherType",
    "CultureTraitType",
    "AnomalyCourtVerdict",
    # Narrative Service Bureau (Phase IX)
    "ParadoxFireDepartment",
    "TemporalArchaeologyDepartment",
    "NarrativeTherapyCenter",
    "TemporalGardeningService",
    "NarrativeChemistryLab",
    "ContinuityInsuranceCompany",
    "TemporalPlumbingService",
    "NarrativeRealEstateAgency",
    "TemporalCateringService",
    "NarrativeLandscapingCompany",
    "TemporalCleaningService",
    "NarrativePestControl",
    # Narrative Service data structures
    "Paradox",
    "FireSuppressionResult",
    "ExcavatedEvent",
    "ArchaeologicalReport",
    "TherapySessionResult",
    "TraumaDiagnosis",
    "PruningResult",
    "StoryElement",
    "StoryCompound",
    "CompoundAnalysis",
    "InsurancePolicy",
    "ContinuityBreach",
    "ClaimResult",
    "RepairResult",
    "DrainResult",
    "StoryLocation",
    "Listing",
    "TransactionResult",
    "NarrativePest",
    "ExterminationResult",
    "SanitizationResult",
    "StoryEnvironment",
    "LandscapedEnvironment",
    # Narrative Service enums
    "ParadoxType",
    "PestType",
    "TraumaSeverity",
    "InsuranceStatus",
    # Phase X - Emergent Governance + Fleet Expansion
    "GovernanceEngine",
    "Constitution",
    "FactionManager",
    "DiplomacyEngine",
    "LawRegistry",
    "LawEngine",
    # Starship Archetypes
    "MythosWeaver",
    "AnomalyHunter",
    "ContinuityGuardian",
]
